# Generated by Django 4.2.8 on 2023-12-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('name',)},
        ),
    ]
