# Generated by Django 4.2.8 on 2023-12-11 15:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight_service", "0003_rename_closes_big_city_airport_closest_big_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("created_at",)},
        ),
    ]
