# Generated by Django 4.2.8 on 2023-12-11 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("flight_service", "0004_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
    ]
